version: "2"
services:
  driver-api:
    build: .
    environment:
    - MONGO_URL=true
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"